# Generated by Django 6.0 on 2026-02-19 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_followers_customuser_folliwing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='folliwing',
            new_name='following',
        ),
    ]
